import { Poppins } from 'next/font/google';
import "@/app/globals.css";
import Header from "@/components/Header";

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata = {
  title: "LinkTree",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable}`}>
        <Header />
        <div className="max-w-4xl mx-auto p-6">{children}</div>
      </body>
    </html>
  );
}
